### ISSUE TITLE
confidence intervals looks different from ggplot2

### ISSUE THREAD

**Issue by OmarAshkar** [jranke/chemCal#1]
Hello,

Thank you for writing this package. I had some observation that I couldn't understand. I run the same sample data with ggplot2 geom_smooth with lm method, the results shows as this for unweighted and weighted model. 
![image](https://github.com/user-attachments/assets/de91e292-3948-4ea5-87be-5ab3353fff6b)

![image](https://github.com/user-attachments/assets/b3a2ff16-0fea-46e8-be94-f34f4966e629)

Then I run the same 2 models with calplot and it seems the confidence interval structure is very different. 

![image](https://github.com/user-attachments/assets/08651fd5-d5ad-4951-99a3-3f6afd48734c)

![image](https://github.com/user-attachments/assets/db6ca98a-2f69-423f-95c7-e0d9b7fa2830)

In general, it seems to my eyes that geom_smooth is respecting both the actual fit and the weights, unless they are different calculations. 

Thank you!

**Comment by jranke** [comment]
Hi, one difference is that you force the model you used for with calplot through zero, which you didn't for the lm method of geom_smooth. In order to see what exactly you did, it would help if you would also post the code you used for generating the model you plotted with calplot.

**Comment by jranke** [comment]
Hi, I do not remember exactly why I did not implement this. However, as a general comment, it seems to me that the `gls` modelling function from the `nlme` package would be the right choice if the error model is what you mentioned. However, the `predict.gls` method does not have the `intervals` argument. It seems to me, adding confidence and prediction intervals to `predict.gls` would be a better way to go about this than doing something in calplot. When using `lm`, specifying the error model in the way you proposed seems like a workaround that is bound to be misleading at some point. With `gls`, it should even possible to use a two-component error

https://stat.ethz.ch/R-manual/R-devel/library/nlme/html/varConstProp.html
